import { IWatchlistItem } from './watchlist.service';
import { EExchange } from '@app/models/common/exchange';
import { EExchangeInstance } from '@app/interfaces/exchange/exchange';
import { EMarketType } from '@app/models/common/marketType';

export const EquitiesWatchlist: IWatchlistItem = {
    id: "defaultEquities",
    name: "Equities US",
    trackingId: "DefaultForex",
    isDefault: true,
    data: [{
        "id": "AAPL",
        "symbol": "AAPL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Apple Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AMD",
        "symbol": "AMD",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Advanced Micro Devices Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AMZN",
        "symbol": "AMZN",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Amazon.com Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "ATVI",
        "symbol": "ATVI",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Activision Blizzard Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BA",
        "symbol": "BA",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Boeing Co-The",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BAC-A",
        "symbol": "BAC-A",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Bank of America Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BIDU",
        "symbol": "BIDU",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Baidu Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "C-J",
        "symbol": "C-J",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Citigroup Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "FB",
        "symbol": "FB",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Facebook Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "FCX",
        "symbol": "FCX",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Freeport-McMoRan Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "FSLR",
        "symbol": "FSLR",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "First Solar Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GM",
        "symbol": "GM",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "General Motors Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GOOG",
        "symbol": "GOOG",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Alphabet Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GOOGL",
        "symbol": "GOOGL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Alphabet Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GS",
        "symbol": "GS",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Goldman Sachs Group Inc-The",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GWPH",
        "symbol": "GWPH",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "GW Pharmaceuticals PLC",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "JPM",
        "symbol": "JPM",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "JPMorgan Chase & Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "MCD",
        "symbol": "MCD",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "McDonald's Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "MSFT",
        "symbol": "MSFT",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Microsoft Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NFLX",
        "symbol": "NFLX",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Netflix Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NKE",
        "symbol": "NKE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "NIKE Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NVDA",
        "symbol": "NVDA",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "NVIDIA Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PFE",
        "symbol": "PFE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Pfizer Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PGHH",
        "symbol": "PGHH",
        "exchange": EExchange.NSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Procter & Gamble Hygiene and Health Care Limited",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PTON",
        "symbol": "PTON",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Peloton Interactive Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "QCOM",
        "symbol": "QCOM",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "QUALCOMM Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "RACE",
        "symbol": "RACE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Ferrari NV",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "SNAP",
        "symbol": "SNAP",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Snap Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "TLRY",
        "symbol": "TLRY",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Tilray Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BYND",
        "symbol": "BYND",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Beyond Meat Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "TSLA",
        "symbol": "TSLA",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Tesla Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "TWTR",
        "symbol": "TWTR",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Twitter Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "UBER",
        "symbol": "UBER",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Uber Technologies Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "WMT",
        "symbol": "WMT",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Walmart Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "XOM",
        "symbol": "XOM",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Exxon Mobil Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "ZM",
        "symbol": "ZM",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Zoom Video Communications Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GE",
        "symbol": "GE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "General Electric Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AAL",
        "symbol": "AAL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "American Airlines Group Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "DELTA",
        "symbol": "DELTA",
        "exchange": EExchange.BSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Delta Industrial Resources Limited",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GPRO",
        "symbol": "GPRO",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "GoPro Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "ACB",
        "symbol": "ACB",
        "exchange": EExchange.TSX,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Aurora Cannabis Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "CUK",
        "symbol": "CUK",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Carnival PLC",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "CCL",
        "symbol": "CCL",
        "exchange": EExchange.BSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "CCL Products ",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NCLH",
        "symbol": "NCLH",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Norwegian Cruise Line Holdings Ltd",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "FIT",
        "symbol": "FIT",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Fitbit Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PLUG",
        "symbol": "PLUG",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Plug Power Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "UAL",
        "symbol": "UAL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "United Airlines Holdings Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "WEED",
        "symbol": "WEED",
        "exchange": EExchange.TSX,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Canopy Growth Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "CSCO",
        "symbol": "CSCO",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Cisco Systems Inc",
        "tradable": false,
        "tickSizeCorrect": true
    }]
};