import { IWatchlistItem } from './watchlist.service';
import { EExchange } from '@app/models/common/exchange';
import { EExchangeInstance } from '@app/interfaces/exchange/exchange';
import { EMarketType } from '@app/models/common/marketType';

export const EquitiesWatchlist: IWatchlistItem = {
    id: "defaultEquities",
    name: "Equities US",
    trackingId: "DefaultForex",
    isDefault: true,
    data: [{
        "id": "AAPL",
        "symbol": "AAPL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Apple Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AMD",
        "symbol": "AMD",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Advanced Micro Devices Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AMZN",
        "symbol": "AMZN",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Amazon.com Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BA",
        "symbol": "BA",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Boeing Co-The",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BAC",
        "symbol": "BAC",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Bank of America Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "BIDU",
        "symbol": "BIDU",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Baidu Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GM",
        "symbol": "GM",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "General Motors Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GOOGL",
        "symbol": "GOOGL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Alphabet Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "JPM",
        "symbol": "JPM",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "JPMorgan Chase & Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "MCD",
        "symbol": "MCD",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "McDonald's Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "MSFT",
        "symbol": "MSFT",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Microsoft Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NFLX",
        "symbol": "NFLX",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Netflix Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NKE",
        "symbol": "NKE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "NIKE Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "NVDA",
        "symbol": "NVDA",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "NVIDIA Corp",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PFE",
        "symbol": "PFE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Pfizer Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "PGHH",
        "symbol": "PGHH",
        "exchange": EExchange.NSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Procter & Gamble Hygiene and Health Care Limited",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "QCOM",
        "symbol": "QCOM",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "QUALCOMM Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "TSLA",
        "symbol": "TSLA",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Tesla Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "UBER",
        "symbol": "UBER",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Uber Technologies Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "WMT",
        "symbol": "WMT",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Walmart Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GE",
        "symbol": "GE",
        "exchange": EExchange.NYSE,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "General Electric Co",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "AAL",
        "symbol": "AAL",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "American Airlines Group Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "GPRO",
        "symbol": "GPRO",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "GoPro Inc",
        "tradable": false,
        "tickSizeCorrect": true
    },
    {
        "id": "CSCO",
        "symbol": "CSCO",
        "exchange": EExchange.NASDAQ,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Stocks,
        "tickSize": 0.01,
        "pricePrecision": 2,
        "baseInstrument": "",
        "dependInstrument": "",
        "company": "Cisco Systems Inc",
        "tradable": false,
        "tickSizeCorrect": true
    }]
};