import { IWatchlistItem } from './watchlist.service';
import { EExchange } from '@app/models/common/exchange';
import { EExchangeInstance } from '@app/interfaces/exchange/exchange';
import { EMarketType } from '@app/models/common/marketType';

export const ExoticsForexWatchlist: IWatchlistItem = {
    id: "defaultForexExotics",
    name: "Forex Exotics",
    trackingId: "ForexExotics",
    isDefault: true,
    data: [{
        "id": "AUD_SGD",
        "symbol": "AUDSGD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SGD",
        "dependInstrument": "AUD",
        "company": "AUD vs SGD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_DKK",
        "symbol": "EURDKK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "DKK",
        "dependInstrument": "EUR",
        "company": "EUR vs DKK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_HKD",
        "symbol": "EURHKD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "HKD",
        "dependInstrument": "EUR",
        "company": "EUR vs HKD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_NOK",
        "symbol": "EURNOK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "NOK",
        "dependInstrument": "EUR",
        "company": "EUR vs NOK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_PLN",
        "symbol": "EURPLN",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "PLN",
        "dependInstrument": "EUR",
        "company": "EUR vs PLN",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_SEK",
        "symbol": "EURSEK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SEK",
        "dependInstrument": "EUR",
        "company": "EUR vs SEK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_SGD",
        "symbol": "EURSGD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SGD",
        "dependInstrument": "EUR",
        "company": "EUR vs SGD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_TRY",
        "symbol": "EURTRY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "TRY",
        "dependInstrument": "EUR",
        "company": "EUR vs TRY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_ZAR",
        "symbol": "EURZAR",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "ZAR",
        "dependInstrument": "EUR",
        "company": "EUR vs ZAR",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "SGD_JPY",
        "symbol": "SGDJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.001,
        "pricePrecision": 3,
        "baseInstrument": "JPY",
        "dependInstrument": "SGD",
        "company": "SGD vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_CNH",
        "symbol": "USDCNH",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CNH",
        "dependInstrument": "USD",
        "company": "USD vs CNH",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_CZK",
        "symbol": "USDCZK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CZK",
        "dependInstrument": "USD",
        "company": "USD vs CZK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_DKK",
        "symbol": "USDDKK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "DKK",
        "dependInstrument": "USD",
        "company": "USD vs DKK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_HKD",
        "symbol": "USDHKD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "HKD",
        "dependInstrument": "USD",
        "company": "USD vs HKD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_MXN",
        "symbol": "USDMXN",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "MXN",
        "dependInstrument": "USD",
        "company": "USD vs MXN",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_NOK",
        "symbol": "USDNOK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "NOK",
        "dependInstrument": "USD",
        "company": "USD vs NOK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_PLN",
        "symbol": "USDPLN",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "PLN",
        "dependInstrument": "USD",
        "company": "USD vs PLN",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD/RUB",
        "symbol": "USDRUB",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Russian Ruble",
        "company": "US Dollar vs Russian Ruble",
        "tradable": false
        },
        {
        "id": "USD_SEK",
        "symbol": "USDSEK",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SEK",
        "dependInstrument": "USD",
        "company": "USD vs SEK",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_THB",
        "symbol": "USDTHB",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.001,
        "pricePrecision": 3,
        "baseInstrument": "THB",
        "dependInstrument": "USD",
        "company": "USD vs THB",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_TRY",
        "symbol": "USDTRY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "TRY",
        "dependInstrument": "USD",
        "company": "USD vs TRY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_ZAR",
        "symbol": "USDZAR",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "ZAR",
        "dependInstrument": "USD",
        "company": "USD vs ZAR",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "NZD_SGD",
        "symbol": "NZDSGD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SGD",
        "dependInstrument": "NZD",
        "company": "NZD vs SGD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_SGD",
        "symbol": "GBPSGD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SGD",
        "dependInstrument": "GBP",
        "company": "GBP vs SGD",
        "tradable": true,
        "tickSizeCorrect": true
        }]
};