import { IWatchlistItem } from './watchlist.service';
import { EExchange } from '@app/models/common/exchange';
import { EExchangeInstance } from '@app/interfaces/exchange/exchange';
import { EMarketType } from '@app/models/common/marketType';

export const ForexWatchlist: IWatchlistItem = {
    id: "defaultForex",
    name: "Forex",
    trackingId: "DefaultForex",
    isDefault: true,
    data: [{
        "id": "EUR/USD",
        "symbol": "EURUSD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "US Dollar",
        "company": "Euro vs US Dollar",
        "tradable": false
    },
    {
        "id": "EUR/CHF",
        "symbol": "EURCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Swiss Franc",
        "company": "Euro vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "EUR/JPY",
        "symbol": "EURJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Japanese Yen",
        "company": "Euro vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "EUR/GBP",
        "symbol": "EURGBP",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "British Pound",
        "company": "Euro vs British Pound",
        "tradable": false
    },
    {
        "id": "EUR/AUD",
        "symbol": "EURAUD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Australian Dollar",
        "company": "Euro vs Australian Dollar",
        "tradable": false
    },
    {
        "id": "EUR/NZD",
        "symbol": "EURNZD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "New Zealand Dollar",
        "company": "Euro vs New Zealand Dollar",
        "tradable": false
    },
    {
        "id": "EUR/CAD",
        "symbol": "EURCAD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Canadian Dollar",
        "company": "Euro vs Canadian Dollar",
        "tradable": false
    },
    {
        "id": "EUR/TRY",
        "symbol": "EURTRY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Turkish Lira",
        "company": "Euro vs Turkish Lira",
        "tradable": false
    },
    {
        "id": "EUR/SEK",
        "symbol": "EURSEK",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Swedish Krona",
        "company": "Euro vs Swedish Krona",
        "tradable": false
    },
    {
        "id": "EUR/NOK",
        "symbol": "EURNOK",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Euro",
        "dependInstrument": "Norwegian Krone",
        "company": "Euro vs Norwegian Krone",
        "tradable": false
    },
    {
        "id": "USD/JPY",
        "symbol": "USDJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Japanese Yen",
        "company": "US Dollar vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "USD/CAD",
        "symbol": "USDCAD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Canadian Dollar",
        "company": "US Dollar vs Canadian Dollar",
        "tradable": false
    },
    {
        "id": "USD/CHF",
        "symbol": "USDCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Swiss Franc",
        "company": "US Dollar vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "USD/TRY",
        "symbol": "USDTRY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Turkish Lira",
        "company": "US Dollar vs Turkish Lira",
        "tradable": false
    },
    {
        "id": "USD/MXN",
        "symbol": "USDMXN",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Mexican Peso",
        "company": "US Dollar vs Mexican Peso",
        "tradable": false
    },
    {
        "id": "USD/ZAR",
        "symbol": "USDZAR",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "South African Rand",
        "company": "US Dollar vs South African Rand",
        "tradable": false
    },
    {
        "id": "USD/CNH",
        "symbol": "USDCNH",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Chinese Yuan (Offshore)",
        "company": "US Dollar vs Chinese Yuan (Offshore)",
        "tradable": false
    },
    {
        "id": "USD/NOK",
        "symbol": "USDNOK",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Norwegian Krone",
        "company": "US Dollar vs Norwegian Krone",
        "tradable": false
    },
    {
        "id": "USD/SEK",
        "symbol": "USDSEK",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "US Dollar",
        "dependInstrument": "Swedish Krona",
        "company": "US Dollar vs Swedish Krona",
        "tradable": false
    },
    {
        "id": "GBP/USD",
        "symbol": "GBPUSD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "US Dollar",
        "company": "British Pound vs US Dollar",
        "tradable": false
    },
    {
        "id": "GBP/JPY",
        "symbol": "GBPJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "Japanese Yen",
        "company": "British Pound vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "GBP/AUD",
        "symbol": "GBPAUD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "Australian Dollar",
        "company": "British Pound vs Australian Dollar",
        "tradable": false
    },
    {
        "id": "GBP/CAD",
        "symbol": "GBPCAD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "Canadian Dollar",
        "company": "British Pound vs Canadian Dollar",
        "tradable": false
    },
    {
        "id": "GBP/NZD",
        "symbol": "GBPNZD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "New Zealand Dollar",
        "company": "British Pound vs New Zealand Dollar",
        "tradable": false
    },
    {
        "id": "GBP/CHF",
        "symbol": "GBPCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "British Pound",
        "dependInstrument": "Swiss Franc",
        "company": "British Pound vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "AUD/USD",
        "symbol": "AUDUSD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Australian Dollar",
        "dependInstrument": "US Dollar",
        "company": "Australian Dollar vs US Dollar",
        "tradable": false
    },
    {
        "id": "AUD/CAD",
        "symbol": "AUDCAD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Australian Dollar",
        "dependInstrument": "Canadian Dollar",
        "company": "Australian Dollar vs Canadian Dollar",
        "tradable": false
    },
    {
        "id": "AUD/JPY",
        "symbol": "AUDJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Australian Dollar",
        "dependInstrument": "Japanese Yen",
        "company": "Australian Dollar vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "AUD/CHF",
        "symbol": "AUDCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Australian Dollar",
        "dependInstrument": "Swiss Franc",
        "company": "Australian Dollar vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "AUD/NZD",
        "symbol": "AUDNZD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Australian Dollar",
        "dependInstrument": "New Zealand Dollar",
        "company": "Australian Dollar vs New Zealand Dollar",
        "tradable": false
    },
    {
        "id": "CAD/JPY",
        "symbol": "CADJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Canadian Dollar",
        "dependInstrument": "Japanese Yen",
        "company": "Canadian Dollar vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "CAD/CHF",
        "symbol": "CADCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "Canadian Dollar",
        "dependInstrument": "Swiss Franc",
        "company": "Canadian Dollar vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "NZD/USD",
        "symbol": "NZDUSD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "New Zealand Dollar",
        "dependInstrument": "US Dollar",
        "company": "New Zealand Dollar vs US Dollar",
        "tradable": false
    },
    {
        "id": "NZD/JPY",
        "symbol": "NZDJPY",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "New Zealand Dollar",
        "dependInstrument": "Japanese Yen",
        "company": "New Zealand Dollar vs Japanese Yen",
        "tradable": false
    },
    {
        "id": "NZD/CHF",
        "symbol": "NZDCHF",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "New Zealand Dollar",
        "dependInstrument": "Swiss Franc",
        "company": "New Zealand Dollar vs Swiss Franc",
        "tradable": false
    },
    {
        "id": "NZD/CAD",
        "symbol": "NZDCAD",
        "exchange": EExchange.Forex,
        "datafeed": EExchangeInstance.TwelvedataExchange,
        "type": EMarketType.Forex,
        "tickSize": 1E-05,
        "pricePrecision": 5,
        "baseInstrument": "New Zealand Dollar",
        "dependInstrument": "Canadian Dollar",
        "company": "New Zealand Dollar vs Canadian Dollar",
        "tradable": false
    }]
};