import { IWatchlistItem } from './watchlist.service';
import { EExchange } from '@app/models/common/exchange';
import { EExchangeInstance } from '@app/interfaces/exchange/exchange';
import { EMarketType } from '@app/models/common/marketType';

export const MinorForexWatchlist: IWatchlistItem = {
    id: "defaultForexMinors",
    name: "Forex Minors",
    trackingId: "ForexMinors",
    isDefault: true,
    data: [{
        "id": "AUD_NZD",
        "symbol": "AUDNZD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "NZD",
        "dependInstrument": "AUD",
        "company": "AUD vs NZD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "AUD_CAD",
        "symbol": "AUDCAD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CAD",
        "dependInstrument": "AUD",
        "company": "AUD vs CAD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "AUD_JPY",
        "symbol": "AUDJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "AUD",
        "company": "AUD vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "CHF_JPY",
        "symbol": "CHFJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "CHF",
        "company": "CHF vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_GBP",
        "symbol": "EURGBP",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "GBP",
        "dependInstrument": "EUR",
        "company": "EUR vs GBP",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_AUD",
        "symbol": "EURAUD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "AUD",
        "dependInstrument": "EUR",
        "company": "EUR vs AUD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_CHF",
        "symbol": "EURCHF",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CHF",
        "dependInstrument": "EUR",
        "company": "EUR vs CHF",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_JPY",
        "symbol": "EURJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "EUR",
        "company": "EUR vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_NZD",
        "symbol": "EURNZD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "NZD",
        "dependInstrument": "EUR",
        "company": "EUR vs NZD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "EUR_CAD",
        "symbol": "EURCAD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CAD",
        "dependInstrument": "EUR",
        "company": "EUR vs CAD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_CHF",
        "symbol": "GBPCHF",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CHF",
        "dependInstrument": "GBP",
        "company": "GBP vs CHF",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_JPY",
        "symbol": "GBPJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "GBP",
        "company": "GBP vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "CAD_CHF",
        "symbol": "CADCHF",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CHF",
        "dependInstrument": "CAD",
        "company": "CAD vs CHF",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "CAD_JPY",
        "symbol": "CADJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "CAD",
        "company": "CAD vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_AUD",
        "symbol": "GBPAUD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "AUD",
        "dependInstrument": "GBP",
        "company": "GBP vs AUD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_CAD",
        "symbol": "GBPCAD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CAD",
        "dependInstrument": "GBP",
        "company": "GBP vs CAD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "GBP_NZD",
        "symbol": "GBPNZD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "NZD",
        "dependInstrument": "GBP",
        "company": "GBP vs NZD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "NZD_CAD",
        "symbol": "NZDCAD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CAD",
        "dependInstrument": "NZD",
        "company": "NZD vs CAD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "NZD_CHF",
        "symbol": "NZDCHF",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "CHF",
        "dependInstrument": "NZD",
        "company": "NZD vs CHF",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "NZD_JPY",
        "symbol": "NZDJPY",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "JPY",
        "dependInstrument": "NZD",
        "company": "NZD vs JPY",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "NZD_USD",
        "symbol": "NZDUSD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "USD",
        "dependInstrument": "NZD",
        "company": "NZD vs USD",
        "tradable": true,
        "tickSizeCorrect": true
        },
        {
        "id": "USD_SGD",
        "symbol": "USDSGD",
        "exchange": EExchange.Oanda,
        "datafeed": EExchangeInstance.OandaExchange,
        "type": EMarketType.Forex,
        "tickSize": 0.00001,
        "pricePrecision": 5,
        "baseInstrument": "SGD",
        "dependInstrument": "USD",
        "company": "USD vs SGD",
        "tradable": true,
        "tickSizeCorrect": true
        }]
};