stages:
    - analize
    - rollout-maintenance
    - build
    - build-image

.npmrc-settings-job: &npmrc-settings-job
    before_script:
        - cp ./.npmrc.template ./.npmrc;
        - sed -i -e "s~TOKEN~$NPM_TOKEN~g" .npmrc;
        #- cat .npmrc

analize-app:
    image: node:12.8.0-alpine
    stage: analize
    <<: *npmrc-settings-job
    script:
        - chmod 777 -R ./
        - echo "NPM Install Chart"
        - npm i trading-chart-designer 
        - echo "NPM Install"
        - npm i 
        - echo "Analize"
        - npm run lint
    # tags:
    #     - web

build-app-stage:
  image: node:12.8.0-alpine
  stage: build
  <<: *npmrc-settings-job
  variables:
    # we override the max_old_space_size to prevent OOM errors
    NODE_OPTIONS: --max_old_space_size=8192
  script:
    - chmod 777 -R ./
    - echo "NPM Cleanup"
    - rm -rf node_modules
    - npm cache clean --force
    - echo "NPM Install Chart"
    - npm i trading-chart-designer 
    - echo "NPM Install"
    - npm i
    - echo "Build"
    - npm run build-stage
  artifacts:
        expire_in: 1 day
        paths:
            - dist/
  only:
    - develop
    - feature/social_feed
#   tags:
#     - web

build-app-prod:
  image: node:12.8.0-alpine
  stage: build
  <<: *npmrc-settings-job
  variables:
    # we override the max_old_space_size to prevent OOM errors
    NODE_OPTIONS: --max_old_space_size=8192
  script:
    - chmod 777 -R ./
    - echo "NPM Cleanup"
    - rm -rf node_modules
    - npm cache clean --force
    - echo "NPM Install Chart"
    - npm i trading-chart-designer 
    - echo "NPM Install"
    - npm i
    - echo "Build"
    - npm run build-prod
  artifacts:
        expire_in: 1 day
        paths:
            - dist/
  only:
    - master
#   tags:
#     - web


build-latest:
    image: docker:stable
    services:
        - docker:dind
    stage: build-image
    script:
        - echo Build Docker Image
        - echo $CI_PROJECT_PATH
        - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH" | tr '[A-Z]' '[a-z]')
        - echo $CONTAINER_IMAGE
        - echo $CI_REGISTRY
        - echo $CI_BUILD_TOKEN
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --tag $CONTAINER_IMAGE:latest .
        - docker push $CONTAINER_IMAGE:latest
    # tags:
    #     - docker
    only:
        - develop
        - feature/social_feed
        - ci-improvements

build-stable:
    image: docker:stable
    services:
        - docker:dind
    stage: build-image
    when: manual
    script:
        - echo Build Docker Image
        - echo $CI_PROJECT_PATH
        - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH" | tr '[A-Z]' '[a-z]')
        - echo $CONTAINER_IMAGE
        - echo $CI_REGISTRY
        - echo $CI_BUILD_TOKEN
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --tag $CONTAINER_IMAGE:stable .
        - docker push $CONTAINER_IMAGE:stable
    # tags:
    #     - docker
    only:
        - master

build-maintenance-stable:
    image: docker:stable
    services:
        - docker:dind
    stage: rollout-maintenance
    when: manual
    script:
        - echo Build Docker Image
        - echo $CI_PROJECT_PATH
        - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH" | tr '[A-Z]' '[a-z]')
        - echo $CONTAINER_IMAGE
        - echo $CI_REGISTRY
        - echo $CI_BUILD_TOKEN
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --tag $CONTAINER_IMAGE:stable -f maintenance.dockerfile .
        - docker push $CONTAINER_IMAGE:stable
    only:
        - master
        
build-maintenance-latest:
    image: docker:stable
    services:
        - docker:dind
    stage: rollout-maintenance
    when: manual
    script:
        - echo Build Docker Image
        - echo $CI_PROJECT_PATH
        - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH" | tr '[A-Z]' '[a-z]')
        - echo $CONTAINER_IMAGE
        - echo $CI_REGISTRY
        - echo $CI_BUILD_TOKEN
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --tag $CONTAINER_IMAGE:latest -f maintenance.dockerfile .
        - docker push $CONTAINER_IMAGE:latest
    only:
        - develop