export const AdminRoutes = {
    AppMembers: 'app-members',
    Blockchains: 'blockchains',
    Chat: 'chat',
    Currencies: 'currencies',
    DataConsolidator: 'data-consolidator',
    Dashboard: 'dashboard',
    Deposits: 'deposits',
    ExchangeMembers: 'exchange-members',
    EventConsolidator: 'event-consolidator',
    Forum: 'forum',
    QA: 'qa',
    Markets: 'markets',
    News: 'news',
    Notifications: 'notifications',
    Orders: 'orders',
    Summary: 'summary',
    SystemMonitoring: 'system-monitoring',
    TradesReports: 'trades-reports',
    Accounts: 'accounts',
    UIPermissionsManager: 'ui-permissions-manager',
    RestrictionsManager: 'restrictions-manager',
    Wallets: 'wallets',
    Withdraws: 'withdraws',
    RunningScripts: 'running-scripts',
    XPDashboard: 'xp-dashboard'
};
